Add minor refinements to description of GitFlow / release approach
miraisolutions/SmaRP pull request #157
Opened 2022-02-15 15:03 UTC by Chargothrond

Neither README files currently contradict anywhere the fact that we now switched to "develop" as the default branch. For this PR, I committed some minor refinements that we may want to update the (GitFlow) README with, given that I anyway reviewed it now.

2022-02-15 20:59 UTC, riccardoporreca requested changes
@Chargothrond, see some minor suggestions.

Besides those, we do miss an important update to the main README though, in that the behavior of

https://github.com/miraisolutions/SmaRP/blob/5166437038c7c550827554ec9366288c889f5156/README.md?plain=1#L27

would nowadays change with the switch to `develop` as default branch, although this is not actually true with the old remotes associated with the version-stable R 3.5.3 environment still used by SmaRP. Let's be always explicit about the branch, and even use the `@<branch>` notation. Overall, I propose the following reshuffling to better support the explicit branches:

~~~md
**SmaRP** is developed using a [GitFlow](git-flow#readme) approach, where the `master` branch always reflects the _latest_ [release](https://github.com/miraisolutions/SmaRP/releases) of the live app, whereas branch `develop` collects the latest delivered developments for the _next_ releases.

The R package **SmaRP** for the latest release can be installed from GitHub with
<!-- argument build_vignettes not available anymore (r-lib/remotes#353), build_opts = "" for a full installation including vignettes  -->
``` r
remotes::install_github("miraisolutions/SmaRP@master", build_opts = "")
```
whereas the development version can be installed via
``` r
remotes::install_github("miraisolutions/SmaRP@develop", build_opts = "")
```

Then, the installed package can be used to serve the app locally from R via
``` r
SmaRP::launch_application()
```
~~~

I tested the behavior of both using the containerized version-stable RStudio approach from our [techguides](https://mirai-solutions.ch/techguides/align-local-development-and-deployment-environments.html#align-local-development-and-deployment-environments). We could also add a new sentence to the paragraph about version-stable (scroll right):

```md
[...] Therefore, the app is developed and tested with the corresponding version of R and packages, as opposed to the latest available versions. This is made easy by the containerized approach to align version-stable development and deployment environments described in our [techguides](https://mirai-solutions.ch/techguides/align-local-development-and-deployment-environments.html#align-local-development-and-deployment-environments).
```

2022-02-15 20:59 UTC, riccardoporreca commented on git-flow/README.md
> +- [**`develop`**](https://github.com/miraisolutions/SmaRP/tree/develop) is set as the default branch and collects all completed developments for the [**next release**](#versioning-and-releases).
Swap, important things first
```suggestion
- [**`develop`**](https://github.com/miraisolutions/SmaRP/tree/develop) collects all completed developments for the [**next release**](#versioning-and-releases) and is set as the default branch.
```

2022-02-15 20:59 UTC, riccardoporreca commented on git-flow/README.md
> +- Only small maintenance work in context of releases can be done directly in `develop` (i.e. only version and `NEWS.md` changes, see also below). Meaningful pieces should be developed in a dedicated
This was never meant to refer to the release but for small things. Still, it is worth mentioning that release preps can happen in develop, deferring to the dedicated session for details.

```suggestion
- Only small maintenance work, including [release preparation](#versioning-and-releases), can be done directly in `develop`. Meaningful pieces should be developed in a dedicated **_feature_ branch** created from `develop` and associated to a GitHub issue (`<ID>`).
```

2022-02-22 09:40 UTC, Chargothrond commented
@riccardoporreca, thanks for the suggestions, I have implemented them.

2022-02-22 11:30 UTC, riccardoporreca approved these changes
LGTM

I changed the PR title and description to reflect the changes introduced ultimately.

2022-02-22 11:32 UTC, riccardoporreca commented on README.md
> +Note that **SmaRP** is deployed using [version-stable](https://github.com/rocker-org/rocker-versioned#readme) images from the [Rocker project](https://www.rocker-project.org/). The target environment
Simplify techguides URL, no need for the anchor
```suggestion
Note that **SmaRP** is deployed using [version-stable](https://github.com/rocker-org/rocker-versioned#readme) images from the [Rocker project](https://www.rocker-project.org/). The target environment of the live app is currently bound to R 3.5.3. Therefore, the app is developed and tested with the corresponding version of R and packages, as opposed to the latest available versions. This is made easy by the containerized approach to align version-stable development and deployment environments described in our [techguides](https://mirai-solutions.ch/techguides/align-local-development-and-deployment-environments.html).
```

2022-02-22 11:40 UTC, merged